// <auto-generated />
using System;
using Atividade2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atividade2.Migrations
{
    [DbContext(typeof(Atividade2Context))]
    partial class Atividade2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atividade2.Models.Confeccoes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Registro");

                    b.Property<int?>("ReposicaoId");

                    b.HasKey("Id");

                    b.HasIndex("ReposicaoId");

                    b.ToTable("Confeccoes");
                });

            modelBuilder.Entity("Atividade2.Models.PecasRoupa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantidade");

                    b.Property<string>("TipoRoupa");

                    b.HasKey("Id");

                    b.ToTable("PecasRoupa");
                });

            modelBuilder.Entity("Atividade2.Models.Confeccoes", b =>
                {
                    b.HasOne("Atividade2.Models.PecasRoupa", "Reposicao")
                        .WithMany()
                        .HasForeignKey("ReposicaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
